BB: {jiggle:1} YOU'RE HERE! {/jiggle}You found me!
BB: I've missed you so much{wave:1}...{/wave}
BB: I don't know {bold:4}what{/bold} happened here... all I know is that I'm stuck
BB: It's this stupid boulder, I assume it's part of the spell that ruined this town and left all of these runes
BB: It wants some code to move, but nothing I tried has worked.
BB: Maybe the runes themselves will hold some clues?