Rac: {jiggle:1} YOU'RE HERE! {/jiggle}You found me!
Rac: I've missed you so much{wave:1}...{/wave}
Rac: I don't know {bold:4}what{/bold} happened here... all I know is that I'm stuck
Rac: It's this stupid boulder, I assume it's part of the spell that ruined this town and left all of these runes
Rac: It wants some code to move, but nothing I tried has worked.
Rac: Maybe the runes themselves will hold some clues?